module: 'Models.Resnets'      # .py file with models (required)
model: 'cifar_resnet20'      # function that creates model (required)
model_parameters:
        block_type: 'original'    # original for Resnet v1, preactivated for Resnet v2
        shortcut_type: 'A'        # A or B as in Deep Residual Learning for Image Recognition
train_parameters:
        logdir: 'logs'            # folder for tensorboard (required)
        run_name: 'resnet20_v1'  # name of the run in tensorboard (required)
        log_interval: 400         # how often statistics are printed and saved to tensorboard
        val_interval: 4000        # how often validation on the test set is done
        batch_size: 256
---
module: 'Models.Resnets'      # .py file with models (required)
model: 'cifar_resnet56'      # function that creates model (required)
model_parameters:
        block_type: 'original'    # original for Resnet v1, preactivated for Resnet v2
        shortcut_type: 'A'        # A or B as in Deep Residual Learning for Image Recognition
train_parameters:
        logdir: 'logs'            # folder for tensorboard (required)
        run_name: 'resnet56_v1'  # name of the run in tensorboard (required)
        log_interval: 400         # how often statistics are printed and saved to tensorboard
        val_interval: 4000        # how often validation on the test set is done
        batch_size: 128
---
module: 'Models.Resnets'      # .py file with models (required)
model: 'cifar_resnet110'      # function that creates model (required)
model_parameters:
        block_type: 'original'    # original for Resnet v1, preactivated for Resnet v2
        shortcut_type: 'A'        # A or B as in Deep Residual Learning for Image Recognition
train_parameters:
        logdir: 'logs'            # folder for tensorboard (required)
        run_name: 'resnet110_v1'  # name of the run in tensorboard (required)
        log_interval: 400         # how often statistics are printed and saved to tensorboard
        val_interval: 4000        # how often validation on the test set is done
        batch_size: 64
